apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-one
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: app-one
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/
          name: conf-vol
        - mountPath: /usr/share/nginx/html
          readOnly: false
          name: data-vol
        - mountPath: /var/log/nginx
          name: log-vol
      volumes:
      - name: conf-vol
        configMap:
          name: app-one
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: data-vol
        hostPath:
          path: /vagrant/confs/html
      - name: log-vol
        emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: app-one
spec:
  ports:
  - port: 80
  selector:
    app: app-one
