
BOX_BASE = "ubuntu2204"
BOX_URL = 
BOX_RAM_MB = "1024"
BOX_CPU_COUNT = "1"


Vagrant.configure("2") do |config|
  
  config.ssh.username = "vagrant"
  config.ssh.insert_key = false
  config.ssh.host = "127.0.0.1"
  config.ssh.guest_port = 22

  config.vm.box = BOX_BASE
  config.vm.box_check_update = false
  # config.vbguest.installer_options = { allow_kernel_upgrade: true }

  config.vm.provider "vmware_desktop" do |vm|
    vm.vmx["memsize"] = BOX_RAM_MB
    vm.vmx["numvcpus"] = BOX_CPU_COUNT
  end

  config.vm.define "Server" do |server|
    server.vm.hostname = "mehillS"
    server.vm.network "private_network", ip: "192.168.56.110", bridged: "wlan0"
    server.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    server.vm.provision "shell", privileged: true, path: "scripts/server.sh", args:["192.168.56.110", "mehillS", "/vagrant/confs/node-token"], run: "always"
    server.vm.provider "vmware_desktop" do |vm|
			vm.name = "mehillS"
		end
  end

  config.vm.network "public_network", bridge: "wlan0"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
