BOX_BASE = "generic/debian11"
BOX_URL = 
BOX_RAM_MB = "4096"
BOX_CPU_COUNT = "4"


Vagrant.configure("2") do |config|
  
  config.ssh.username = "vagrant"
  config.ssh.insert_key = false
  # config.ssh.host = "127.0.0.1"
  # config.ssh.guest_port = 22
  # config.ssh.private_key_path = "~/.ssh/id_rsa"
  # config.ssh.forward_agent = true

  config.vm.box = BOX_BASE
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = BOX_CPU_COUNT
    vb.memory = BOX_RAM_MB
  end

  config.vm.define "GitlabRunner" do |server|
    server.vm.hostname = "GitlabRunner"
    server.vm.network "private_network", ip: "192.168.56.112", bridged: "wlan0"
    server.vm.synced_folder ".", "/home/vagrant", type: "virtualbox"
    # server.vm.provision "shell", privileged: true, path: "scripts/setup.sh", args:[], run: "always"
    server.vm.provider "virtualbox" do |vm|
			vm.name = "GitlabRunner"
		end
  end

  config.vm.network "public_network", bridge: "wlan0"


  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

end
